
[functions.create_invite]
enabled = true
verify_jwt = false
import_map = "./functions/create_invite/deno.json"
entrypoint = "./functions/create_invite/index.ts"

[functions.accept_invite]
enabled = true
verify_jwt = false
import_map = "./functions/accept_invite/deno.json"
entrypoint = "./functions/accept_invite/index.ts"

[functions.finalize_game]
enabled = true
verify_jwt = false
entrypoint = "./functions/finalize_game/index.ts"

[functions.create_rematch_invite]
enabled = true
verify_jwt = false
entrypoint = "./functions/create_rematch_invite/index.ts"

[functions.decline_invite]
enabled = true
verify_jwt = false
entrypoint = "./functions/decline_invite/index.ts"

[functions.create_ai_game]
enabled = true
verify_jwt = false
entrypoint = "./functions/create_ai_game/index.ts"
